spring:
  application:
    name: sistema de cadastro
  datasource:
    url: jdbc:h2:mem:tarefas
    username: luisa
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true